### ISSUE TITLE
Add docs to public API

### ISSUE THREAD

**Issue by phptek** [smindel/silverstripe-gis#14]
The README documents several useful `DataList` producing methods on the `GIS` class, but each of which have no docs to help devs understand what they do (and why they're so named). For example, what does "ewkt" mean / stand for?

**Comment by smindel** [comment]
Version 1.3.0 saw a major restructuring of the docs. The ORM filters are now documented here: https://github.com/smindel/silverstripe-gis/blob/master/docs/en/ORM-Filters.md

EWKT = extended well known text, now explained here: https://github.com/smindel/silverstripe-gis/blob/master/docs/en/GIS.md
