### ISSUE TITLE
WithinGeo filter doesn't seem to work

### ISSUE THREAD

**Issue by phptek** [smindel/silverstripe-gis#16]
To reproduce (using v1.1.3)

* Create a basic `Page` with a `Location` field as `Geometry`
* In the SilverStripe admin area, use leaflet to designate a single Polygon around the whole of the Wellington region (for example)
* Now create a `TestModel` as a `DataObject` subclass, that also has a `Location` field as `Geometry` and set that location value, as any polygon located within the Page's geometry, e.g. around the shape of Te Papa's building footprint
* Now construct an ORM query somewhere that attempts to return a count of 1, for the no. `Page` records, that intersect or are within the geometry of the one `TestModel` you just created, somethuing like this:

```
        $coords = (array) $request->postVar('coords');
        $srid = Config::inst()->get(GIS::class, 'default_srid');
        $records = PlanPage::get()->filter([
            'Location:WithinGeo' => GIS::array_to_ewkt($coords, $srid, true),
        ]);
```

Note: As discussed, there should prob be a unit-test to cover the `WithinGeo` filter :-)

[UPDATE]

I was partly being an idiot, in that I was relying too hard on expected behviour. In a standard SilverStripe `FormField` subclass, changing the value, re-renders the "Publish" button, as SilverStripe detects that something has changed. It is _this_ that isn't happening for the `MapField`. SilverStripe simply wasn't recognising that a change had ocurred. Once I made a change to a _different_ field, the "Publish" button highlighted itself, and publishing wrote the right Geometry string to the xx_Live table.

**Comment by phptek** [comment]
A simplified query that returns the expected single row:

```
SELECT * FROM "SomePage" WHERE (ST_Intersects(ST_GeomFromText('POLYGON((174.78122057099 -41.2900367890677,174.781886102042 -41.2902302628832,174.782658976811 -41.2896982085099,174.78289513299 -41.2898271917867,174.782701914298 -41.2902947540276,174.782852195503 -41.2904721043458,174.782487226862 -41.2910202750086,174.781113227272 -41.2906655768704,174.78122057099 -41.2900367890677))', 4326),"SomePage"."Location"))
```

One that doesn't work (containing multple SIlverStripe JOIN's)

```
SELECT DISTINCT "SiteTree_Live"."ClassName", "SiteTree_Live"."LastEdited", "SiteTree_Live"."Created", "SiteTree_Live"."CanViewType", "SiteTree_Live"."CanEditType", "SiteTree_Live"."Version", "SiteTree_Live"."URLSegment", "SiteTree_Live"."Title", "SiteTree_Live"."MenuTitle", "SiteTree_Live"."Content", "SiteTree_Live"."MetaDescription", "SiteTree_Live"."ExtraMeta", "SiteTree_Live"."ShowInMenus", "SiteTree_Live"."ShowInSearch", "SiteTree_Live"."Sort", "SiteTree_Live"."HasBrokenFile", "SiteTree_Live"."HasBrokenLink", "SiteTree_Live"."ReportClass", "SiteTree_Live"."ParentID", "Page_Live"."LandingPageSummary", "Page_Live"."LandingPageSummaryImageID", "SomePage_Live"."Type", "SomePage_Live"."Label", "SomePage_Live"."Address", "SomePage_Live"."Name", "SomePage_Live"."Abstract", ST_AsEWKT("SomePage_Live"."Location") "Location", "SiteTree_Live"."ID", CASE WHEN "SiteTree_Live"."ClassName" IS NOT NULL THEN "SiteTree_Live"."ClassName" ELSE E'SilverStripe\\CMS\\Model\\SiteTree' END AS "RecordClassName" FROM "SiteTree_Live" LEFT JOIN "Page_Live" ON "Page_Live"."ID" = "SiteTree_Live"."ID" LEFT JOIN "SomePage_Live" ON "SomePage_Live"."ID" = "SiteTree_Live"."ID" WHERE (ST_Intersects(ST_GeomFromText('POLYGON((174.78122057099 -41.2900367890677,174.781886102042 -41.2902302628832,174.782658976811 -41.2896982085099,174.78289513299 -41.2898271917867,174.782701914298 -41.2902947540276,174.782852195503 -41.2904721043458,174.782487226862 -41.2910202750086,174.781113227272 -41.2906655768704,174.78122057099 -41.2900367890677))', 4326),"SomePage_Live"."Location")) ORDER BY "SiteTree_Live"."Sort" ASC
```

**Comment by phptek** [comment]
I have traced this back to a failed `JOIN`. For some reason ,using `MapField` in `updateCMSFields()` in a `DataExtension` on `Page`, failes to populate the "Location" field on the page's xx_Live table.

**Comment by smindel** [comment]
Sorry, I can't reproduce this issue. It is working fine for me:

Page.php with Geometry field saved and published successful using the CMS.
