### ISSUE TITLE
If silverstripe/postgresql package is not installed, throw meaningful exception

### ISSUE THREAD

**Issue by phptek** [smindel/silverstripe-gis#17]
At the moment in `PostgreSQLSchemaManager`:

```
if (!class_exists(PostgreSQLSchemaManager::class)) {
    return;
}
```

Consider throwing an `Exception` "Postgres package not installed"

**Comment by smindel** [comment]
The above is to drop out of executing the following class definition in situations where Postgres is not installed, so MySQL users don't get a fatal error when compiling the class manifest. The absence of PostgreSQLSchemaManager is not an error, hence no Exception should be thrown.
