### ISSUE TITLE
GeoJsonService::getConfig() makes incorrect assumptions for property_map

### ISSUE THREAD

**Issue by phptek** [smindel/silverstripe-gis#18]
`GeoJsonService::index()` calls `GeoJsonService::getConfig()` which always uses the module's default, baked-in value for the value of `property_map`, even if API consumers specify one as follows in their model(s), as such, a leafletJS map was taking the wrong `DataObject` field. With a patched module (incoming...) this will work as expected.

```
    /**
     * @var array
     */
    private static $geojsonservice = [
        'geometry_field' => 'Location',
        'searchable_fields' => [
            'Address',
            'Location',
        ],
        'property_map' => [
            'ID' => 'id',
            'Type' => 'type',
        ],
    ];
```

It appears that `GeoJsonService::getConfig()` isn't really needed and that the default for `property_map` can be added to the other defaults in `AbstractGISWebServiceController::getConfig()`.

**Comment by smindel** [comment]
Can't reproduce
