### ISSUE TITLE
UI Map/CMS search UI overlay issue

### ISSUE THREAD

**Issue by phptek** [smindel/silverstripe-gis#20]
When using the CMS' internal search feature in 4.x, the fine-tuning search box/dropdown dialgoue is hidden behind the map's `<div>`. See screenshot below.

![map-overlay-bug](https://user-images.githubusercontent.com/478440/53130399-016e0280-35cf-11e9-96f8-588e74a4c3f3.png)

**Comment by smindel** [comment]
good catch. fixed in  3447df4
cheers
