### ISSUE TITLE
ST_Distance ORM Filter docs 

### ISSUE THREAD

**Issue by sparkcom** [smindel/silverstripe-gis#27]
Hello @smindel , 

Many thanks for making this module available. It has been very useful. 

Wonder if there is an error in the sample codes in the docs where it says: 
`$city = City::get()->filter('Name', 'Wellington')->first();

$distance = 100000; // metres

$degrees = $distance / 111195;

$cities = Cities::get()->filter('Location:ST_Contains', [$city->Location, $degrees]);`

Shouldn't it be  
`$cities = Cities::get()->filter('Location:ST_Distance', [$city->Location, $degrees]);`

Also, the value of $city->Location is a string in this format 
POINT(lat lng),4332 

Am I correct? 

Regards,
Ben

**Comment by smindel** [comment]
Yes you are correct. Thanks for reporting. Fixed
