### ISSUE TITLE
 Problems with monolog.

### ISSUE THREAD

**Issue by ed5on** [smindel/silverstripe-gis#28]
When installing the package it returns the following problems:
![image](https://user-images.githubusercontent.com/25689934/92728013-083da100-f33e-11ea-95ba-e5a5f6eada5a.png)
I am using laravel 7.24 and php 7.4.6

**Comment by smindel** [comment]
This is a Silverstripe (not Laravel, different framework) module, extending the Silverstripe ORM. It is incompatible with Laravel.
